// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * TrackSyncDetail 对应 Java TrackSyncDetail，映射 track_sync_detail 表
 */
export class TrackSyncDetail {
    /**
     * Creates a new TrackSyncDetail instance.
     * @param {Partial<TrackSyncDetail>} [$$source = {}] - The source object to create the TrackSyncDetail.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("mdNo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mdNo"] = "";
        }
        if (!("trackStatus" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["trackStatus"] = null;
        }
        if (!("eventDesc" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["eventDesc"] = null;
        }
        if (!("eventTime" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["eventTime"] = null;
        }
        if (!("createTime" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createTime"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrackSyncDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TrackSyncDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrackSyncDetail(/** @type {Partial<TrackSyncDetail>} */($$parsedSource));
    }
}
