// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService Wails 暴露给前端的唯一服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig 获取当前配置（密码脱敏）
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetConfig() {
    return $Call.ByID(402027511).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetDashboardStats 获取仪表盘统计数据
 * @returns {$CancellablePromise<$models.DashboardStats>}
 */
export function GetDashboardStats() {
    return $Call.ByID(2768787382).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetOrderDetails 获取单个订单的轨迹事件
 * @param {string} mdNo
 * @returns {$CancellablePromise<model$0.TrackSyncDetail[]>}
 */
export function GetOrderDetails(mdNo) {
    return $Call.ByID(3045777295, mdNo).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetOrders 获取订单列表
 * @param {number} pageSize
 * @returns {$CancellablePromise<$models.OrderListItem[]>}
 */
export function GetOrders(pageSize) {
    return $Call.ByID(276078524, pageSize).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetRecentLogs 获取最近的同步日志
 * @param {number} limit
 * @returns {$CancellablePromise<$models.LogEntry[]>}
 */
export function GetRecentLogs(limit) {
    return $Call.ByID(3963199861, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * IsConfigured 检查是否已配置完成
 * @returns {$CancellablePromise<boolean>}
 */
export function IsConfigured() {
    return $Call.ByID(2708601167);
}

/**
 * OnShutdown Wails 生命周期 - 服务关闭时调用
 * @returns {$CancellablePromise<void>}
 */
export function OnShutdown() {
    return $Call.ByID(1004802248);
}

/**
 * OnStartup Wails 生命周期 - 服务启动时调用
 * @param {application$0.ServiceOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function OnStartup(options) {
    return $Call.ByID(1361655147, options);
}

/**
 * SaveConfig 保存配置（从前端传入完整配置）
 * @param {{ [_ in string]?: any }} cfgData
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(cfgData) {
    return $Call.ByID(628243056, cfgData);
}

/**
 * TriggerSync 手动触发同步
 * @returns {$CancellablePromise<void>}
 */
export function TriggerSync() {
    return $Call.ByID(428074554);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.DashboardStats.createFrom;
const $$createType2 = model$0.TrackSyncDetail.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.OrderListItem.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.LogEntry.createFrom;
const $$createType7 = $Create.Array($$createType6);
