// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DashboardStats 仪表盘统计数据
 */
export class DashboardStats {
    /**
     * Creates a new DashboardStats instance.
     * @param {Partial<DashboardStats>} [$$source = {}] - The source object to create the DashboardStats.
     */
    constructor($$source = {}) {
        if (!("totalOrders" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalOrders"] = 0;
        }
        if (!("delivered" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["delivered"] = 0;
        }
        if (!("inTransit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["inTransit"] = 0;
        }
        if (!("isSyncRunning" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isSyncRunning"] = false;
        }
        if (!("lastSyncTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastSyncTime"] = "";
        }
        if (!("lastSyncError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastSyncError"] = "";
        }
        if (!("schedulerEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["schedulerEnabled"] = false;
        }
        if (!("cronSpec" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cronSpec"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DashboardStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DashboardStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DashboardStats(/** @type {Partial<DashboardStats>} */($$parsedSource));
    }
}

/**
 * LogEntry 日志条目
 */
export class LogEntry {
    /**
     * Creates a new LogEntry instance.
     * @param {Partial<LogEntry>} [$$source = {}] - The source object to create the LogEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("mdNo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mdNo"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("eventDesc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["eventDesc"] = "";
        }
        if (!("eventTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["eventTime"] = "";
        }
        if (!("createTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry(/** @type {Partial<LogEntry>} */($$parsedSource));
    }
}

/**
 * OrderListItem 订单列表项
 */
export class OrderListItem {
    /**
     * Creates a new OrderListItem instance.
     * @param {Partial<OrderListItem>} [$$source = {}] - The source object to create the OrderListItem.
     */
    constructor($$source = {}) {
        if (!("mdNo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mdNo"] = "";
        }
        if (!("fid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fid"] = "";
        }
        if (!("trackStatus" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["trackStatus"] = null;
        }
        if (!("lastEvent" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["lastEvent"] = null;
        }
        if (!("isDelivered" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDelivered"] = false;
        }
        if (!("lastSyncTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastSyncTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OrderListItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OrderListItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OrderListItem(/** @type {Partial<OrderListItem>} */($$parsedSource));
    }
}
